[tool.poetry]
name = "national_memographic"
version = "0.1.5"
description = "The one and only Twitter meme bot"
authors = ["hacksparr0w <hacksparr0w@protonmail.com>"]
license = "MIT"
include = ["data/**/*"]

[tool.poetry.dependencies]
python = "^3.7"
Wand = "^0.6.6"
click = "^8.0.1"
requests = "^2.26.0"
requests_oauthlib = "^1.3.0"

[tool.poetry.dev-dependencies]
mypy = "^0.910"
pylint = "^2.9.6"
flake8 = "^3.9.2"
pytest = "^6.2.4"
types-requests = "^2.25.2"

[tool.poetry.scripts]
meme = "national_memographic.__main__:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
