[tool.poetry]
name = "musamusa_romannumbers"
version = "0.1.3"
description = "Roman Numbers (XVI <-> 16)"
authors = ["suizokukan <suizokukan@orange.fr>"]
license = "GPLv3"

[tool.poetry.dependencies]
python = "^3.9"
musamusa-errors = "^0.9.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
