[tool.poetry]
name = "todus3"
homepage = "https://github.com/oleksis/todus/tree/todus3"
repository = "https://github.com/oleksis/todus/tree/todus3"
version = "0.9.0"
description = "ToDus client for S3"
authors = ["adbenitez <adbenitez@nauta.cu>"]
maintainers = ["Oleksis Fraga <oleksis.fraga@gmail.com>"]
license = "MPL"
readme = "README.md"
keywords = ["todus" , "s3", "client"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
    "Operating System :: OS Independent",
    "Topic :: Utilities"
]

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.25.1"
tqdm = "^4.61.2"
multivolumefile = { version = "^0.2.3", optional = true }
py7zr = { version = "^0.16.1", optional = true }

[tool.poetry.extras]
7z = ["multivolumefile", "py7zr"]

[tool.poetry.dev-dependencies]
black = {version = "^21.6b0", python = ">3.6.2"}
flake8 = "^3.9.2"
mypy = "^0.910"
types-requests = "^2.25.0"
pytest = "^6.2.4"
pyinstaller = "^4.4"

[tool.poetry.scripts]
todus3 = 'todus3.main:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
