[tool.poetry]
name = "cst_geometry"
version = "0.1.0"
description = "Package for modeling in CST Microwave studio using python"
authors = ["konstantgr <konstantin.grotov@metalab.ifmo.ru>"]
license = "MIT"
readme = "README.rst"
repository = "https://github.com/konstantgr/cst_geometry_manager"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
