[tool.poetry]
name = "musamusa_textref"
version = "0.2.2"
description = "\"Beowulf.4c\" < \"Beowulf.5a\""
authors = ["suizokukan <suizokukan@orange.fr>"]
license = "GPLv3"

[tool.poetry.dependencies]
python = "^3.9"
musamusa-romannumbers = "^0.1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
