[tool.poetry]
name = "NeogiInstruments"
version = "2.6.1"
description = "Communication and helper functions for lab equipment"
authors = ["UNT Neogi Lab <BrianSquires@my.unt.edu>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.9"
pyserial = "^3.5"
nidaqmx = "^0.5.7"
matplotlib = "^3.4.2"
plotly = "^5.0.0"
param = "^1.10.1"
PyMeasure = "^0.9.0"
pandas = "^1.3.0"
scipy = "^1.7.0"
tabulate = "^0.8.9"
panel = "^0.11.3"
pigpio = "^1.78"
pyusb = "^1.2.0"
Instrumental-lib = "^0.6"
h5py = "^3.3.0"
PyVISA-py = "^0.5.2"
PyVISA = "^1.11.3"
[tool.poetry.scripts]
port_table = 'neogiinstruments.ports:port_table'


[tool.poetry.dev-dependencies]
elliptec = { git = 'https://github.com/UNTNeogiLab/TL-rotation-control' }
k10cr1 = { git = 'https://github.com/QuantumQuadrate/k10cr1' }
stellarnet = { git = "git@github.com:UNTNeogiLab/stellarnet.git", branch = "main"}
pyvcam = { git ="git@github.com:UNTNeogiLab/pyvcam.git", branch = "master"} #comment out to make it work without pvcam
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
