[tool.poetry]
name = "gsdcli"
version = "0.3.10"
description = "A cli for installing game servers"
authors = ["egee-irl <brian@egee.io>"]

[tool.poetry.dependencies]
python = "^3.7"
Click = "^7.1.1"
pyyaml = "^5.3.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.9.2"
black = "^21.7b0"

[tool.poetry.scripts]
gsdcli = "gsdcli.gsdcli:gsdcli"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
