[tool.poetry]
name = "communauto"
version = "0.1.3"
description = ""
authors = ["Hadrien David <hadrien@ectobal.com>"]


[tool.poetry.dependencies]
python = "^3.9"
typer = "^0.3.2"
httpx = "^0.18.1"
pydantic = "^1.8.2"
pytz = "^2021.1"
structlog = "^21.1.0"
tabulate = "^0.8.9"
colorama = "^0.4.4"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
pytest-asyncio = "^0.15.1"
pytest-cov = "^2.12.1"
respx = "^0.17.0"
black = "^21.6b0"
pylama = "^7.7.1"
mypy = "^0.902"
pytest-watch = "^4.2.0"
pdbpp = "^0.10.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
communauto = 'communauto:main'
