[tool.poetry]
name = "asai-ciel"
version = "1.0.4"
description = ""
authors = ["haripo <haripo@users.noreply.github.com>"]
packages = [
    { include = "ciel" },
]
include = [
    "models/**/*",
    "scripts/analyze_video.py"
]

[tool.poetry.scripts]
analyze_video = "scripts.analyze_video:main"

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.3.1"
tensorflow = "^2.5.0"
click = ">=7.0"
colorama = "^0.4.4"
asai-abyss = "^0.3.2"
tqdm = "^4.62.0"
opencv-python-headless = "^4.0"
scikit-learn = "^0.24.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
pytest-benchmark = "^3.4.1"
mypy = "^0.910"
coverage = "^5.5"
types-setuptools = "^57.0.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
